### ISSUE TITLE
 Issue with S3 Bucket Folder Displaying 4G in VM Terminal

### ISSUE THREAD

**Issue by rfeng2023** [rfeng2023/mmcloud#128] opened 2024-12-11 15:00 UTC
I have encountered an issue where the S3 bucket folder mounted on my VM terminal shows only 4G of storage when using the df command. This creates a storage issue when attempting to download files using wget.

However, I can successfully copy files larger than 4G from my VM home folder to the S3 bucket. This discrepancy indicates that the issue might be related to how the S3 bucket is being displayed or mounted on the VM ( maybe limited to wget but I am not sure).
![image](https://github.com/user-attachments/assets/d6f8b987-63ca-4bc2-aea7-43920ad9b8b7)

**Comment by gaow** [comment] 2024-12-11 15:48
@siwei12101900 I wonder if it is something that Achyutha as the AWS expert might have some insight on? 

A shorter summary + motivation: this behavior prevents us from directly download to AWS S3 bucket via an VM for anything > 4G. Since the download is not simply running `wget` it is part of a package installation script that download some data in the installation process, we have to use a VM rather than other AWS alternatives to get data directly on the bucket.

**Comment by Ashley-Tung** [comment] 2024-12-11 18:12
Taking a look, I am going to start my own jupyter instance to see if get the same behavior

**Comment by Ashley-Tung** [comment] 2024-12-11 18:42
I have also asked this in the slack, but @rfeng2023, can you provide me an example wget command that was not working for you? And can you show me what happens when you wget into the data? What error message shows, if there are any?

**Comment by gaow** [comment] 2024-12-12 15:33
> What tool is downloading such large files automatically? While we should resolve this issue regardless, it would be nice to know what needs this much data in case there are engineering improvements to be made as well.

It is the NIAGADS FILER database (Pavel's work) with its own conventions and ways to handle the engineering details. We use it as is without intention to modify at this stage.

**Comment by Ashley-Tung** [comment] 2024-12-12 18:45
Is there a special way it is `wget`ting data into the s3?

**Comment by danielnachun** [comment] 2024-12-12 18:48
I see that it's a collection of shell scripts and the downloads are just `wget` calls.  I'll work on a conda package for the scripts so they be installed with `pixi`, but for the data downloads there's nothing that could be done from an engineering perspective anyway.  The data needs to be downloaded regardless, and it's not always possible to split a large file into 4GB chunks.

@Ashley-Tung the script call `wget` is here: https://bitbucket.org/wanglab-upenn/filer/src/master/install_filer.sh.  It loops over a large list of files and downloads them.  It should just be using this `wget` command:
```
wget -N '${url}' -o "${tgDir}/${tgFname}"
```
As far as I know this the "standard" way to download files like this.

**Comment by Ashley-Tung** [comment] 2024-12-12 18:50
ok I'll see if this behavior happens to me too

**Comment by Ashley-Tung** [comment] 2024-12-13 18:25
@gaow or @rfeng2023 , what command did you use to run the `install_filled.sh` script? Currently, I just got to testing running it up to the `wget` command, but i need other parameters to run this

**Comment by Ashley-Tung** [comment] 2024-12-13 18:25
Or if you know the actual file that gets `wget`'ed that would be helpful too

**Comment by Ashley-Tung** [comment] 2024-12-19 17:42
Did some more digging and engineering confirmed this might actually be a known s3fs bug that has been fixed in our upcoming build 3.1. As we are on 3.03 and unsure when 3.1 will be released, I am currently asking them to provide an extra build for 3.03 regarding this issue

**Comment by Ashley-Tung** [comment] 2024-12-20 23:35
Hi @gaow , I have upgraded the opcenters to a new build that resolves this issue. You should be able to see updated information on the mounts now - it is no longer showing the 4GB. For jobs that have been suspended when we were still using the earlier version, I believe resuming them should use the fix as well.
![image](https://github.com/user-attachments/assets/37eaf2bd-6497-4653-b2d2-890dd5d1daaf)

**Closed** 2024-12-23 16:22 UTC
